# Generated by Django 5.2.5 on 2025-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("provider", "Provider"), ("seeker", "Seeker")],
                max_length=10,
                null=True,
            ),
        ),
    ]
