# Generated by Django 5.2.5 on 2025-09-22 06:12

from django.db import migrations


def migrate_worker_to_provider(apps, schema_editor):
    """Migrate existing 'worker' user types to 'provider'"""
    UserProfile = apps.get_model('profiles', 'UserProfile')
    UserProfile.objects.filter(user_type='worker').update(user_type='provider')


def reverse_migrate_provider_to_worker(apps, schema_editor):
    """Reverse migration: change 'provider' back to 'worker'"""
    UserProfile = apps.get_model('profiles', 'UserProfile')
    UserProfile.objects.filter(user_type='provider').update(user_type='worker')


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.RunPython(
            migrate_worker_to_provider,
            reverse_migrate_provider_to_worker,
        ),
    ]
