# Generated by Django 5.2.5 on 2025-09-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_auto_20250922_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="languages",
            field=models.TextField(
                blank=True, help_text="Languages spoken by the user", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="provider_id",
            field=models.CharField(
                blank=True,
                help_text="Unique provider ID (2 letters + 8 digits)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
