# Generated by Django 5.2.5 on 2025-09-23 06:17

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_userprofile_languages_userprofile_provider_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("worker", "Worker"),
                    ("driver", "Driver"),
                    ("properties", "Properties"),
                    ("SOS", "Emergency Services"),
                ],
                help_text="Service type for providers",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="languages",
            field=models.TextField(
                blank=True,
                help_text="Languages spoken by the user as comma-separated",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DriverServiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_types",
                    models.TextField(
                        blank=True,
                        help_text="Vehicle types as comma-separated",
                        null=True,
                    ),
                ),
                ("license_number", models.CharField(max_length=50)),
                ("vehicle_registration_number", models.CharField(max_length=20)),
                ("driving_years_experience", models.IntegerField()),
                ("driving_experience_description", models.TextField()),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_service",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyServiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_types",
                    models.TextField(
                        blank=True,
                        help_text="Property types as comma-separated",
                        null=True,
                    ),
                ),
                ("property_title", models.CharField(max_length=200)),
                (
                    "parking_availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                            ("street_parking", "Street Parking"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "furnishing_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("furnished", "Furnished"),
                            ("semi_furnished", "Semi Furnished"),
                            ("unfurnished", "Unfurnished"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("property_description", models.TextField()),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_service",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SOSServiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emergency_service_types",
                    models.TextField(
                        blank=True,
                        help_text="Emergency service types as comma-separated",
                        null=True,
                    ),
                ),
                ("contact_number", models.CharField(max_length=15)),
                ("current_location", models.TextField()),
                ("emergency_description", models.TextField()),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_service",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServicePortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.core.models.user_profile_photo_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                            apps.core.models.validate_image_size,
                        ],
                    ),
                ),
                ("image_order", models.IntegerField()),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_portfolio_images",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["image_order"],
                "unique_together": {("user_profile", "image_order")},
            },
        ),
    ]
