# Generated by Django 5.2.5 on 2025-09-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0005_userprofile_service_type_alter_userprofile_languages_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverservicedata",
            old_name="driving_years_experience",
            new_name="years_experience",
        ),
    ]
