# Generated by Django 5.2.5 on 2025-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0006_rename_driving_years_experience_driverservicedata_years_experience",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyservicedata",
            name="parking_availability",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=20,
                null=True,
            ),
        ),
    ]
