# Generated by Django 5.2.5 on 2025-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_update_parking_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyservicedata",
            name="furnishing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fully Furnished", "Fully Furnished"),
                    ("Semi Furnished", "Semi Furnished"),
                    ("Unfurnished", "Unfurnished"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
