# Generated by Django 5.2.5 on 2025-09-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_communicationsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                help_text="Firebase Cloud Messaging token for push notifications",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_active_for_work",
            field=models.BooleanField(
                default=False,
                help_text="Provider is actively available for work assignments",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.CharField(
                        help_text="Type of service requested", max_length=100
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Additional message from seeker"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "distance",
                    models.CharField(
                        blank=True,
                        help_text="Distance between seeker and provider",
                        max_length=50,
                    ),
                ),
                (
                    "seeker_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "seeker_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "provider_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "provider_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "response_time",
                    models.DateTimeField(
                        blank=True, help_text="When provider responded", null=True
                    ),
                ),
                (
                    "completion_time",
                    models.DateTimeField(
                        blank=True, help_text="When work was completed", null=True
                    ),
                ),
                (
                    "fcm_sent",
                    models.BooleanField(
                        default=False, help_text="FCM notification was sent"
                    ),
                ),
                (
                    "websocket_sent",
                    models.BooleanField(
                        default=False, help_text="WebSocket message was sent"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seeker_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkAssignmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("work_assigned", "Work Assigned"),
                            ("work_accepted", "Work Accepted"),
                            ("work_rejected", "Work Rejected"),
                            ("work_completed", "Work Completed"),
                            ("work_cancelled", "Work Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("fcm", "FCM"), ("websocket", "WebSocket")],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "fcm_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="profiles.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["seeker", "status"], name="profiles_wo_seeker__8d00f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["provider", "status"], name="profiles_wo_provide_b5f159_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["status", "created_at"], name="profiles_wo_status_ac05e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workassignmentnotification",
            index=models.Index(
                fields=["work_order", "notification_type"],
                name="profiles_wo_work_or_967c7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workassignmentnotification",
            index=models.Index(
                fields=["recipient", "delivery_status"],
                name="profiles_wo_recipie_02e939_idx",
            ),
        ),
    ]
