# Generated by Django 5.2.5 on 2025-10-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_add_work_assignment_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("five_star_count", models.PositiveIntegerField(default=0)),
                ("four_star_count", models.PositiveIntegerField(default=0)),
                ("three_star_count", models.PositiveIntegerField(default=0)),
                ("two_star_count", models.PositiveIntegerField(default=0)),
                ("one_star_count", models.PositiveIntegerField(default=0)),
                (
                    "provider",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "provider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_summary",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review_text", models.TextField()),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "provider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date"],
            },
        ),
    ]
