# Generated by Django 5.2.5 on 2025-10-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_providerrating_providerreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="distance",
        ),
        migrations.AddField(
            model_name="workorder",
            name="calculated_distance",
            field=models.FloatField(
                blank=True, help_text="Calculated distance in kilometers", null=True
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="main_category_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Main category code (e.g., MS0001)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="schedule_data",
            field=models.JSONField(
                blank=True, help_text="Schedule information from frontend", null=True
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="sub_category_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sub category code (e.g., SS0001)",
                max_length=20,
            ),
        ),
    ]
