# Generated by Django 5.2.5 on 2025-10-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_remove_workorder_distance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "user_profile",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "provider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Wallet",
                "verbose_name_plural": "Provider Wallets",
            },
        ),
    ]
