# Generated by Django 5.2.5 on 2025-10-08 03:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "connection_state",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for medium selection"),
                            ("active", "Active connection"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "seeker_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "seeker_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "seeker_last_location_update",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "provider_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "provider_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "provider_last_location_update",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("current_distance_meters", models.FloatField(blank=True, null=True)),
                ("last_distance_update", models.DateTimeField(blank=True, null=True)),
                (
                    "seeker_selected_mediums",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'telegram': '9876543210', 'whatsapp': '9876543210', 'call': '9876543210'}",
                    ),
                ),
                (
                    "provider_selected_mediums",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'telegram': '9876543210', 'whatsapp': '9876543210', 'call': '9876543210'}",
                    ),
                ),
                ("mediums_shared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat_room_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("chat_started_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="profiles.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TypingIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("seeker", "Seeker"), ("provider", "Provider")],
                        max_length=10,
                    ),
                ),
                ("is_typing", models.BooleanField(default=False)),
                ("last_typing_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_indicators",
                        to="profiles.worksession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("seeker", "Seeker"), ("provider", "Provider")],
                        help_text="Anonymous sender type",
                        max_length=10,
                    ),
                ),
                ("message_text", models.TextField()),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="profiles.worksession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(
                fields=["session_id"], name="profiles_wo_session_93cc6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(
                fields=["work_order"], name="profiles_wo_work_or_eb6a9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(
                fields=["connection_state"], name="profiles_wo_connect_f8c4aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="typingindicator",
            index=models.Index(
                fields=["session", "user"], name="profiles_ty_session_e67fa9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="typingindicator",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="profiles_ch_session_ec6b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["message_id"], name="profiles_ch_message_6669e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["expires_at"], name="profiles_ch_expires_62514b_idx"
            ),
        ),
    ]
