# Generated by Django 5.2.5 on 2025-10-08 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_worksession_typingindicator_chatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked the service as finished",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worksession",
            name="rating_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Rating description/review from seeker",
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="rating_stars",
            field=models.IntegerField(
                blank=True,
                help_text="Rating from 1-5 stars (only from seeker to provider)",
                null=True,
            ),
        ),
    ]
