# Generated by Django 5.2.5 on 2025-10-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_worksession_completed_by_worksession_rated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offer_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique offer ID",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Offer title", max_length=200)),
                ("description", models.TextField(help_text="Offer description")),
                (
                    "image_url",
                    models.URLField(help_text="Offer image URL", max_length=500),
                ),
                (
                    "valid_until",
                    models.DateTimeField(help_text="Offer validity end date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Offer active status"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=999,
                        help_text="Display priority (lower number = higher priority)",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="App maintenance mode (affects all users)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "ordering": ["priority", "-created_at"],
            },
        ),
    ]
