# Generated by Django 5.2.5 on 2025-10-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksession",
            name="connection_state",
            field=models.CharField(
                choices=[
                    ("active", "Active connection"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
