# Generated by Django 5.2.5 on 2025-10-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_alter_worksession_connection_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="last_online_payment_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time ₹20 was paid for going online",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="online_subscription_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 24-hour online period expires",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(help_text="Transaction description")),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance after transaction",
                        max_digits=10,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="profiles.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
