# Generated by Django 5.2.5 on 2025-10-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_wallet_last_online_payment_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationsettings",
            name="land_mark",
            field=models.CharField(
                blank=True,
                help_text="Physical landmark or address",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communicationsettings",
            name="upi_ID",
            field=models.CharField(
                blank=True, help_text="UPI payment ID", max_length=100, null=True
            ),
        ),
    ]
