# Generated by Django 5.2.5 on 2025-10-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_communicationsettings_land_mark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_role_switch_date",
            field=models.DateTimeField(
                blank=True, help_text="Last time user switched roles", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="previous_user_type",
            field=models.CharField(
                blank=True,
                choices=[("provider", "Provider"), ("seeker", "Seeker")],
                help_text="Previous user type before role switch",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role_switch_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times user has switched roles"
            ),
        ),
        migrations.CreateModel(
            name="RoleSwitchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user_type",
                    models.CharField(
                        blank=True,
                        choices=[("provider", "Provider"), ("seeker", "Seeker")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "to_user_type",
                    models.CharField(
                        choices=[("provider", "Provider"), ("seeker", "Seeker")],
                        max_length=10,
                    ),
                ),
                ("switch_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for role switch",
                        null=True,
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_switch_history",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Switch History",
                "verbose_name_plural": "Role Switch Histories",
                "ordering": ["-switch_date"],
            },
        ),
    ]
