# Generated by Django 5.2.5 on 2025-10-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_userprofile_last_role_switch_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "verbose_name": "User Wallet",
                "verbose_name_plural": "User Wallets",
            },
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to="profiles.userprofile",
            ),
        ),
    ]
