# Generated by Django 5.2.5 on 2025-10-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_remove_wallet_provider_constraint"),
    ]

    operations = [
        # Rename the model from DriverServiceData to VehicleServiceData
        migrations.RenameModel(
            old_name="DriverServiceData",
            new_name="VehicleServiceData",
        ),
        # Update the related_name for the relationship
        migrations.AlterField(
            model_name="vehicleservicedata",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_service",
                to="profiles.userprofile",
            ),
        ),
        # Update the service_type choices
        migrations.AlterField(
            model_name="userprofile",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skill", "Skill"),
                    ("vehicle", "Vehicle"),
                    ("properties", "Properties"),
                    ("SOS", "Emergency Services"),
                ],
                help_text="Service type for providers",
                max_length=15,
                null=True,
            ),
        ),
    ]
