# Generated by Django 5.2.5 on 2025-10-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_rename_driver_to_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyservicedata",
            name="service_offering_types",
            field=models.TextField(
                blank=True,
                help_text="Service offering types as comma-separated (rent, sale, lease, all)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="business_location",
            field=models.CharField(
                blank=True,
                help_text="Business location/address",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="business_name",
            field=models.CharField(
                blank=True,
                help_text="Business name for business-type seekers",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="established_date",
            field=models.DateField(
                blank=True, help_text="Date when business was established", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="seeker_type",
            field=models.CharField(
                blank=True,
                choices=[("individual", "Individual"), ("business", "Business")],
                help_text="Type of seeker (individual or business)",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="service_coverage_area",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Service coverage area in kilometers (how far the provider can travel)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Business website (optional)",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicleservicedata",
            name="service_offering_types",
            field=models.TextField(
                blank=True,
                help_text="Service offering types as comma-separated (rent, sale, lease, all)",
                null=True,
            ),
        ),
    ]
