# Generated by Django 5.2.5 on 2025-10-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0023_propertyservicedata_service_offering_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="Business website (optional, no validation)",
                max_length=300,
                null=True,
            ),
        ),
    ]
