# Generated by Django 5.1 on 2025-11-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_userprofile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleservicedata',
            name='vehicle_types',
        ),
    ]
