# Generated by Django 5.2.5 on 2025-10-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0018_wallet_last_online_payment_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referral_code_used",
                    models.CharField(
                        help_text="The provider_id used as referral code", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        help_text="Referral status",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the referral was successfully registered",
                    ),
                ),
                (
                    "referred_provider",
                    models.OneToOneField(
                        help_text="The new provider who used a referral code",
                        limit_choices_to={"user_type": "provider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_info",
                        to="profiles.userprofile",
                    ),
                ),
                (
                    "referrer_provider",
                    models.ForeignKey(
                        help_text="The existing provider who shared the referral code",
                        limit_choices_to={"user_type": "provider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Referral",
                "verbose_name_plural": "Provider Referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("referrer", "Referrer Reward"),
                            ("referee", "Referee Reward"),
                        ],
                        help_text="Type of reward: referrer (100 Rs) or referee (50 Rs)",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Reward amount", max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "is_credited",
                    models.BooleanField(
                        default=False, help_text="Whether reward was credited to wallet"
                    ),
                ),
                (
                    "credited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When reward was credited to wallet",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_rewards",
                        to="profiles.userprofile",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="referrals.providerreferral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Reward",
                "verbose_name_plural": "Referral Rewards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="providerreferral",
            index=models.Index(
                fields=["referrer_provider", "-created_at"],
                name="referrals_p_referre_bd2314_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providerreferral",
            index=models.Index(
                fields=["referred_provider"], name="referrals_p_referre_9faa39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["provider", "-created_at"],
                name="referrals_r_provide_fb87d2_idx",
            ),
        ),
    ]
