# Generated by Django 5.2.5 on 2025-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0025_remove_vehicleservicedata_vehicle_types"),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="providerreferral",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("referred_provider", models.F("referrer_provider")), _negated=True
                ),
                name="no_self_referral",
            ),
        ),
    ]
