# Generated by Django 5.2.5 on 2025-08-15 05:32

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AadhaarVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[apps.core.validators.validate_aadhaar_number],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("otp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("can_skip", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aadhaar_verification",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LicenseVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[apps.core.validators.validate_license_number],
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("driving", "Driving License"),
                            ("commercial", "Commercial License"),
                            ("other", "Other"),
                        ],
                        default="driving",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_verification",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
