# Generated by Django 5.2.5 on 2025-09-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("work_categories", "0004_rename_skills_description_userworkselection_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="seekersearchpreference",
            name="searching_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="work_categories.worksubcategory",
            ),
        ),
    ]
