# Generated by Django 5.2.5 on 2025-09-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcategory",
            name="category_code",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="worksubcategory",
            name="subcategory_code",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
    ]
