# Generated by Django 5.2.5 on 2025-09-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_categories", "0003_servicerequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userworkselection",
            old_name="skills_description",
            new_name="skills",
        ),
    ]
